version: "3.9"

services:
  webserver:
    build: .
    container_name: '${COMPOSE_PROJECT_NAME}-webserver'
    restart: always
    ports:
      - "${HOST_PORT}:80"
    volumes:
      -  ./src/:/var/www/html
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: '${COMPOSE_PROJECT_NAME}-database'
    restart: always
    ports:
      - "127.0.0.1:${DB_PORT}:3306"
    volumes: 
      - 'mysqldata:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mysqldata:
    driver: local